# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GMM' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GMM
pod 'Firebase/Auth'
pod 'Firebase/Firestore'
pod 'Firebase/Storage'
pod 'Firebase/Database'
pod 'CodableFirebase'
pod 'FirebaseUI/Storage'
pod 'Kingfisher'
pod 'SwiftPhotoGallery'
pod 'FirebaseFirestoreSwift'
pod 'FirebaseCore'
pod 'GoogleSignIn'
pod 'FBSDKCoreKit'
pod 'FBSDKShareKit'

end
